name: CI

on:
  push:
    branches: [master, beta]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test

  build:
    name: Building project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: build
        run: |
          yarn build:ts
          cpx package.json dist/package.json

  release:
    name: Releasing
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist
          yarn semantic-release
